var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/(dashboard)/projects/new/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1vknp-k._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1l4kws0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__15ypo8t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_1iylvrn._.js")
R.c("server/chunks/ssr/src_11rqi_a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/[root-of-the-server]__1caoue8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__160xfli._.js")
R.c("server/chunks/ssr/_0pjz0_8._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_(dashboard)_projects_new_page_actions_1ohed8s.js")
R.m(94771)
module.exports=R.m(94771).exports
