var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/(dashboard)/page.js")
R.c("server/chunks/ssr/node_modules_next_dist_1y2xy7w._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qmob0d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_1ivs2qn._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_0d323sd._.js")
R.c("server/chunks/ssr/node_modules_next_dist_server_route-modules_app-page_0qo_rmc._.js")
R.c("server/chunks/ssr/[externals]__05yr04l._.js")
R.c("server/chunks/ssr/_0myy_h8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/node_modules_@vercel_oidc_dist_00g90j9._.js")
R.c("server/chunks/ssr/node_modules_next_1_rutxl._.js")
R.c("server/chunks/ssr/node_modules_jose_dist_node_cjs_0739t5s._.js")
R.c("server/chunks/ssr/node_modules_@vercel_cli-config_dist_index_1d7q-il.js")
R.c("server/chunks/ssr/node_modules_undici_1bvcd0c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1l45vz4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bnx_-_._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_(dashboard)_page_actions_176do11.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/admin/(dashboard)/page { METADATA_0 => \"[project]/src/app/favicon.ico.mjs { IMAGE => \\\"[project]/src/app/favicon.ico (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript)\", MODULE_1 => \"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/src/app/admin/(dashboard)/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/src/app/admin/(dashboard)/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/admin/(dashboard)/page { METADATA_0 => \"[project]/src/app/favicon.ico.mjs { IMAGE => \\\"[project]/src/app/favicon.ico (static in ecmascript, tag client)\\\" } [app-rsc] (structured image object, ecmascript)\", MODULE_1 => \"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/node_modules/next/dist/client/components/builtin/not-found.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/node_modules/next/dist/client/components/builtin/global-error.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/src/app/admin/(dashboard)/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/src/app/admin/(dashboard)/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)").exports
