var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/login/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0a_j4u1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1l4kws0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__15ypo8t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_1iylvrn._.js")
R.c("server/chunks/ssr/src_11rqi_a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/[root-of-the-server]__1033qvv._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0hj-4tg._.js")
R.c("server/chunks/ssr/_0pjz0_8._.js")
R.m(53277)
module.exports=R.m(53277).exports
